/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amd_aparapi_device_OpenCLDevice_OpenCLInvocationHandler */

#ifndef _Included_com_amd_aparapi_device_OpenCLDevice_OpenCLInvocationHandler
#define _Included_com_amd_aparapi_device_OpenCLDevice_OpenCLInvocationHandler
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
