/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amd_aparapi_Kernel_FlowType */

#ifndef _Included_com_amd_aparapi_Kernel_FlowType
#define _Included_com_amd_aparapi_Kernel_FlowType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
