/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amd_aparapi_internal_jni_RangeJNI */

#ifndef _Included_com_amd_aparapi_internal_jni_RangeJNI
#define _Included_com_amd_aparapi_internal_jni_RangeJNI
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
