/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amd_aparapi_device_Device */

#ifndef _Included_com_amd_aparapi_device_Device
#define _Included_com_amd_aparapi_device_Device
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
