/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amd_aparapi_Range */

#ifndef _Included_com_amd_aparapi_Range
#define _Included_com_amd_aparapi_Range
#ifdef __cplusplus
extern "C" {
#endif
#undef com_amd_aparapi_Range_THREADS_PER_CORE
#define com_amd_aparapi_Range_THREADS_PER_CORE 16L
#undef com_amd_aparapi_Range_MAX_OPENCL_GROUP_SIZE
#define com_amd_aparapi_Range_MAX_OPENCL_GROUP_SIZE 1024L
#ifdef __cplusplus
}
#endif
#endif
