/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amd_aparapi_internal_opencl_OpenCLMem */

#ifndef _Included_com_amd_aparapi_internal_opencl_OpenCLMem
#define _Included_com_amd_aparapi_internal_opencl_OpenCLMem
#ifdef __cplusplus
extern "C" {
#endif
#undef com_amd_aparapi_internal_opencl_OpenCLMem_MEM_DIRTY_BIT
#define com_amd_aparapi_internal_opencl_OpenCLMem_MEM_DIRTY_BIT 32768L
#undef com_amd_aparapi_internal_opencl_OpenCLMem_MEM_COPY_BIT
#define com_amd_aparapi_internal_opencl_OpenCLMem_MEM_COPY_BIT 65536L
#undef com_amd_aparapi_internal_opencl_OpenCLMem_MEM_ENQUEUED_BIT
#define com_amd_aparapi_internal_opencl_OpenCLMem_MEM_ENQUEUED_BIT 131072L
#ifdef __cplusplus
}
#endif
#endif
