/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amd_aparapi_Config */

#ifndef _Included_com_amd_aparapi_Config
#define _Included_com_amd_aparapi_Config
#ifdef __cplusplus
extern "C" {
#endif
#undef com_amd_aparapi_Config_enableGETSTATIC
#define com_amd_aparapi_Config_enableGETSTATIC 1L
#ifdef __cplusplus
}
#endif
#endif
