SETLOCAL
SET HERE=%~dp0
FOR %%X IN ("%ATISTREAMSDKROOT%") DO SET ATISTREAMSDKROOT=%%~sX
FOR %%X IN ("%HERE%") DO SET HERE=%%~sX
SET PATH=%PATH%;%ATISTREAMSDKROOT%\bin\x86
SET PATH=%PATH%;%ATISTREAMSDKROOT%\bin\x86\xp
SET PATH=%PATH%;%HERE%
%JAVA_HOME%/bin/java -jar %1 %2 %3 %4 %5 %6 %7 %8 %9 
ENDLOCAL

